---
- name: restart uwsgi processes
  supervisorctl: name=${project.name}_uwsgi state=restarted

- name: start uwsgi process
  supervisorctl: name=${project.name}_uwsgi state=started

- name: touch uwsgi deployment file
  shell: touch ${project.root}/deployment
  #file: path=${project.root}/deployment state=touch
