---
- name: reload supervisor
  action: service name=supervisor state=reloaded

- name: restart uwsgi processes
  supervisorctl: name=${project.name}_uwsgi state=restarted config=/var/opt/my_project/supervisord.conf

- name: touch uwsgi deployment file
  shell: touch ${project.root}/deployment
