- name: "Set up CI server"
  hosts: jenkins
  user: root

  vars:
    pkg_mgr: ${ansible_pkg_mgr}

  tasks:
   - name: Install packages
     action: $pkg_mgr name=$item state=latest
     with_items:
       - python2.7-dev
       - python-pip
       - mercurial
       - nodejs
       - npm

       - binutils
       - libproj-dev
       - gdal-bin

   - name: Install Python packages
     action: pip name=$item
     with_items:
        - virtualenv
