---
- name: Install psycopg2 package
  apt: pkg=python-psycopg2 state=installed update-cache=yes
  tags:
    - packages

- name: Create user
  postgresql_user: user=${project.database.user} password=${project.database.password}
  sudo_user: postgres

- name: Create database
  postgresql_db: name=${project.database.name} owner=${project.database.user}
                 encoding="UTF-8" lc_collate="en_US.UTF-8"
                 lc_ctype="en_US.UTF-8" template="template0"
  sudo_user: postgres
