---
- name: Create user account
  user: name=${project.user} state=present

- name: Create project directories
  file: state=directory path=${project.root}/${item}/ owner=${project.user} group=${project.user}
  with_items:
    - logs
    - virtualenv
    - webapp
    - static

- name: Install supervisor config
  action: template src=supervisor.j2 dest=/etc/supervisor/conf.d/${project.name}.conf

- name: Pull source from the repository
  git: repo=${project.repo} dest=${project.root}/webapp/ version=${project.revision} update=yes force=yes

- name: Install requirements
  pip: requirements=${project.root}/webapp/requirements.txt virtualenv=${project.root}/virtualenv

- name: Collect static files
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/configs/${project.environment}/manage.py collectstatic --noinput

- name: Sync database
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/configs/${project.environment}/manage.py syncdb --noinput

- name: Migrate database
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/configs/${project.environment}/manage.py migrate --noinput
  notify:
    - touch uwsgi deployment file
