---
- name: Create user account
  user: name=${project.user} state=present

- name: Create main project directory
  file: state=directory path=${project.root} owner=${project.user} group=${project.user} mode=0755

- name: Create project directories
  file: state=directory path=${project.root}/${item.name}/ owner=${project.user} group=${project.user} mode=${item.mode}
  with_items:
    - { "name": "logs", "mode": "0755"}
    - { "name": "virtualenv", "mode": "0755"}
    - { "name": "configs", "mode": "0755"}
    - { "name": "private", "mode": "0411"}
    - { "name": "webapp", "mode": "0755"}
    - { "name": "static", "mode": "0755"}
    - { "name": "uploads", "mode": "0755"}

- name: Install private webserver files
  copy: src=${project.environment}/${item} dest=${project.root}/private/${item} owner=${project.www_user} group=${project.www_group} mode=0400
  with_items:
    - htpasswd-admin
    - localhost.crt
    - localhost.key

- name: Install Python configs
  action: template src=${item.src} dest=${project.root}/webapp/mailytics/configs/${item.dest} owner=${project.user} group=${project.user}
  with_items:
    - { "src": "settings.py.j2", "dest": "local_settings.py" }
    - { "src": "wsgi.py.j2", "dest": "wsgi.py" }

- name: Install uwsgi_params file
  copy: src=uwsgi_params dest=${project.root}/configs/uwsgi_params owner=${project.www_user} group=${project.www_group}

- name: Install nginx config
  action: template src=nginx.conf.j2 dest=/etc/nginx/conf.d/mailytics.conf owner=root group=root

- name: Install supervisor config
  action: template src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/${project.name}.conf

- name: Install uwsgi config
  action: template src=uwsgi.ini.j2 dest=${project.root}/configs/uwsgi.ini owner=${project.user} group=${project.user}

- name: Pull source from the repository
  git: repo=${project.repo} dest=${project.root}/webapp/ version=${project.revision} update=yes force=yes

- name: Install requirements
  pip: requirements=${project.root}/webapp/requirements.txt virtualenv=${project.root}/virtualenv

- name: Collect static files
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/manage.py collectstatic --noinput
  environment:
    DJANGO_SETTINGS_MODULE: "${project.settings_module}"

- name: Sync database
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/manage.py syncdb --noinput
  environment:
    DJANGO_SETTINGS_MODULE: "${project.settings_module}"

- name: Migrate database
  shell: ${project.root}/virtualenv/bin/python ${project.root}/webapp/mailytics/manage.py migrate --noinput
  environment:
    DJANGO_SETTINGS_MODULE: "${project.settings_module}"
  notify:
    - reload supervisor
    - reload nginx
    - start uwsgi process
    - touch uwsgi deployment file
