- name: Create main project directory
  file: state=directory path=${project.root} owner=${project.user} group=${project.user} mode=0755

- name: Create project directories
  file: state=directory path=${project.root}/${item.name}/ owner=${project.user} group=${project.user} mode=${item.mode}
  with_items:
    - { "name": "logs", "mode": "0755"}
    - { "name": "virtualenv", "mode": "0755"}
    - { "name": "configs", "mode": "0755"}
    - { "name": "data", "mode": "0711"}
    - { "name": "backups", "mode": "0711"}
    - { "name": "private", "mode": "0511"}

- name: Pull source from the repository
  git: repo=${project.repo} dest=${project.root}/code/ version=${project.revision} update=yes force=yes
  notify:
    - reload supervisor
    - restart celery beat
    - restart celery workers

- name: Install requirements
  pip: requirements=${project.root}/code/requirements.txt virtualenv=${project.root}/virtualenv

- name: Install templatized config files
  action: template src=${item.src} dest=${item.dest} owner=${item.owner} group=${item.group}
  with_items:
    - { "src": "supervisor.conf.j2", "dest": "${project.root}/configs/supervisor.conf", "owner": "${project.user}", "group": "${project.user}" }
    - { "src": "settings.py.j2", "dest": "${project.root}/configs/settings.py", "owner": "${project.user}", "group": "${project.user}" }
  notify:
    - reload supervisor
    - restart celery beat
    - restart celery workers

- name: Symlink configs
  file: src=${item.src} dest=${item.dest} state=link force=yes
  with_items:
    - { "src": "${project.root}/configs/supervisor.conf", "dest": "/etc/supervisor/conf.d/${project.name}.conf" }
    - { "src": "${project.root}/configs/settings.py", "dest": "${project.root}/code/workers/local_settings.py" }
