---
project:
  name: mailytics_token_storage
  user: mailyticstokenstorage

  repo: git@github.com:Kami/mailytics-services.git
  root: /data-deploy/mailytics-token-storage

  environment: development
  revision: master

  service_args: --database_path=${project.root}/data/database.sqlite --ca_file=${project.root}/private/ca.crt --cert_file=${project.root}/private/server.crt --key_file=${project.root}/private/server.key --private_keys_path=${project.root}/private/private_keys/
