---
- name: Install common system packages
  apt: pkg=${item} state=installed update-cache=yes
  with_items: ${common.packages}
  tags:
    - packages

- name: Install customer sudoers config
  copy: src=sudoers.conf dest=/etc/sudoers.d/0001-preserve-auth-sock.conf validate='visudo -cf %s'
